export type TProduct = {
  _id: string;
  title: string;
  slug?: string;
  quantity: number;
  soldQuantity?: number;
  mrpPrice: number;
  discount?: number;
  discountType?: string;
  price: number;
  availableQuantity?: number;
  short_details: string;
  description: string;
  category: string;
  subCategory?: string;
  brand?: string;
  thumbal_image: string;
  backview_image?: string | null | undefined;
  images: string[];
  video_url?: string;
  size_chart?: string;
  freeShipping?: boolean;
  weight?: string;
  sku?: string;
  barcode?: string;
  stock_status?: string;
  inventoryType?: string;
  labels?: string;
};