import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AdminPanelLayout from "../components/Admin-panal/admin-layout";
import { SidebarProvider } from "../context/Sidebar_Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider>
          <AdminPanelLayout>{children}</AdminPanelLayout>
        </SidebarProvider>
      </body>
    </html>
  );
}
