import shirt from "@/src/assets/product/product.jpg";

export const orderList = [
  {
    id: 1,
    title: "PRODUCT NAME HERE",
    orderID: "ZARGANZ123",
    price: 3500,
    image: shirt,
    date: "2024-06-15",
    status: "Delivered",
    paymentmethod: "cash on delivery",
  },
  {
    id: 2,
    title: "Zara Women Leather Bag",
    orderID: "ZARGANZ123",
    price: 3500,
    image: shirt,
    date: "2024-06-15",
    status: "cancelled",
    paymentmethod: "cash on delivery",
  },
  {
    id: 3,
    title: "Travel Leather Backpack",
    orderID: "ZARGANZ123",
    price: 3500,
    image: shirt,
    date: "2024-06-15",
    status: "Shipped",
    paymentmethod: "cash on delivery",
  },
  {
    id: 4,
    title: "PRODUCT NAME HERE",
    orderID: "ZARGANZ123",
    price: 3500,
    image: shirt,
    date: "2024-06-15",
    status: "Delivered",
    paymentmethod: "Online",
  },
  {
    id: 5,
    title: "PRODUCT NAME HERE",
    orderID: "ZARGANZ123",
    price: 3500,
    image: shirt,
    date: "2024-06-15",
    status: "cancelled",
    paymentmethod: "cash on delivery",
  },
  {
    id: 6,
    title: "PRODUCT NAME HERE",
    orderID: "ZARGANZ123",
    price: 3500,
    image: shirt,
    date: "2024-06-15",
    status: "pending",
    paymentmethod: "Online",
  },
];
