import shirt from "@/src/assets/product/product.jpg";

export const productList = [
  {
    id: 1,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "In Stock",
    rating: 4.5,
    discountType: "flat",
    discount: 120,
    price: 3500,
    mrpPrice: 4201,
    inventoryType: "size",
    image: shirt,
    category: "Handbags",
    subcategory: "watches",
    childcategory: "watches",
    label: "",
    code: "ZARGANZ123",
    stok: "100",
  },
  {
    id: 2,
    title: "Zara Women Leather Bag",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "In Stock",
    rating: 4.5,
    price: 500,
    mrpPrice: 600,
    discountType: "flat",
    inventoryType: "color",
    discount: "110",
    image: shirt,
    category: "watches",
    subcategory: "watches",
    childcategory: "watches",
    label: "",
    code: "ZARGANZ2045",
    stok: "100",

  },
  {
    id: 3,
    title: "Travel Leather Backpack",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "Out of Stock",
    rating: 4.5,
    price: 350,
    mrpPrice: 400,
    discount: "80",
    discountType: "flat",
    inventoryType: "colorsize",
    category: "Shoes",
    image: shirt,
    subcategory: "watches",
    childcategory: "watches",
    label: "",
    code: "WEBSE2045",
    stok: "100",
  },
  {
    id: 4,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "In Stock",
    rating: 4.5,
    price: 7580,
    mrpPrice: 8000,
    discount: 200,
    discountType: "flat",
    inventoryType: "colorsize",
    category: "Perfume",
    image: shirt,
    subcategory: "watches",
    childcategory: "watches",
    label: "",
    code: "TSSE2045",
    stok: "100",
  },
  {
    id: 5,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "Out of Stock",
    rating: 4.5,
    price: 3500,
    mrpPrice: "820",
    discount: "60",
    discountType: "flat",
    inventoryType: "size",
    category: "Handbags",
    image: shirt,
    subcategory: "watches",
    childcategory: "watches",
    label: "box packaging",
    code: "YAAS2045",
    stok: "100",
  },
  {
    id: 6,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "Out of Stock",
    rating: 4.5,
    price: 1280,
    mrpPrice: "980",
    image: shirt,
    category: "Perfume",
    subcategory: "watches",
    childcategory: "watches",
    discount: 80,
    discountType: "flat",
    inventoryType: "color",
    label: "",
    code: "QEAS2045",
    stok: "100",
  },
  {
    id: 7,
    title: "iPhone 8 Plus 64GB Full Color",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "In Stock",
    rating: 4.5,
    price: 620,
    mrpPrice: 700,
    discount: 60,
    discountType: "flat",
    inventoryType: "",
    image: shirt,
    category: "watches",
    subcategory: "watches",
    childcategory: "watches",
    label: "new arrival",
    code: "XXEAS2045",
    stok: "100",
  },
  {
    id: 8,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "In Stock",
    rating: 4.5,
    discount: 120,
    discountType: "flat",
    inventoryType: "color",
    price: 3500,
    mrpPrice: 4201,
    image: shirt,
    category: "Handbags",
    subcategory: "watches",
    childcategory: "",
    label: "",
    code: "ZARGANZ123",
    stok: "100",
  },

  {
    id: 9,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "In Stock",
    rating: 4.5,
    discount: 120,
    discountType: "flat",
    inventoryType: "color",
    price: 3500,
    mrpPrice: 4201,
    image: shirt,
    category: "Handbags",
    subcategory: "",
    childcategory: "watches",
    label: "",
    code: "ZARGANZ123",
    stok: "100",
  },
  {
    id: 10,
    title: "Zara Women Leather Bag",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "In Stock",
    rating: 4.5,
    price: 500,
    mrpPrice: 600,
    discount: 120,
    discountType: "flat",
    image: shirt,
    inventoryType: "size",
    category: "watches",
    subcategory: "",
    childcategory: "",
    label: "",
    code: "ZARGANZ2045",
    stok: "100",
  },
  {
    id: 11,
    title: "Zara Women Leather Bag",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "In Stock",
    rating: 4.5,
    price: 500,
    mrpPrice: 600,
    discount: 120,
    discountType: "flat",
    image: shirt,
    inventoryType: "colorsize",
    category: "watches",
    subcategory: "watches",
    childcategory: "watches",
    label: "",
    code: "ZARGANZ2045",
    stok: "100",
  },
  {
    id: 12,
    title: "Travel Leather Backpack",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "Out of Stock",
    rating: 4.5,
    image: shirt,
    price: 350,
    mrpPrice: 400,
    discount: 120,
    discountType: "flat",
    inventoryType: "color",
    category: "Shoes",
    subcategory: "watches",
    childcategory: "watches",
    label: "",
    code: "WEBSE2045",
    stok: "100",
  },
];
